name: Deploy to GitHub Pages

on:
    push:
      tags:
        - 'v*'
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.9' # Set the Swift version you need

    - name: Build DocC
      run: |
        swift package --allow-writing-to-directory ./ \
            generate-documentation --target NotPrivateAPIs \
            --disable-indexing \
            --transform-for-static-hosting \
            --experimental-enable-custom-templates \
            --hosting-base-path / \
            --output-path ./Build \

        echo "<script>window.location.href += \"/documentation/notprivateapis\"</script>" > Build/index.html;
    
    # - name: Prepare relative files
    #   run: |
    #     python3 ./path-replacement.py

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'Build'
    - id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4